use std::{env, fs, path::PathBuf};

const GENERATED: &str = r#"// Generated by homebot-protocol/examples/export_android.rs. Do not edit.
package dev.homebot.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

const val PROTOCOL_VERSION: Int = 1

@Serializable
sealed interface ClientMessage {
    @Serializable @SerialName("hello")
    data class Hello(val protocol_version: Int, val client_version: String, val device_session: String, val resume_after: Long? = null) : ClientMessage
    @Serializable @SerialName("command")
    data class Command(val request_id: String, val idempotency_key: String, val command: CommandBody) : ClientMessage
    @Serializable @SerialName("cancel")
    data class Cancel(val request_id: String, val operation_id: String) : ClientMessage
    @Serializable @SerialName("pong")
    data class Pong(val nonce: String) : ClientMessage
}

@Serializable
sealed interface CommandBody {
    @Serializable @SerialName("create_bot")
    data class CreateBot(val name: String, val title: String) : CommandBody
    @Serializable @SerialName("send_message")
    data class SendMessage(val chat_id: String, val content: String) : CommandBody
}

@Serializable
data class ServerEvent(
    val protocol_version: Int,
    val sequence: Long,
    val event_id: String,
    val kind: String,
    val request_id: String? = null,
    val operation_id: String? = null,
    val payload: JsonElement? = null,
)

@Serializable
data class ErrorEnvelope(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val request_id: String? = null,
    val retry_after_ms: Long? = null,
    val details: JsonElement? = null,
)

@Serializable
data class BotAdvancedSettings(
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class BotSummary(
    val id: String,
    val name: String,
    val title: String,
    val description: String,
    val shape: String,
    val color: String,
    val archived: Boolean,
    val unread_count: Int,
    val attention: String,
    val provider: String,
    val advanced: BotAdvancedSettings,
)

@Serializable
data class CreateBotRequest(
    val request_id: String,
    val idempotency_key: String,
    val name: String,
    val title: String,
    val description: String = "",
    val shape: String,
    val color: String,
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class UpdateBotRequest(
    val request_id: String,
    val idempotency_key: String,
    val name: String,
    val title: String,
    val description: String = "",
    val shape: String,
    val color: String,
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class BotMutationRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class BotResponse(val bot: BotSummary)

@Serializable
data class ChatSummary(
    val id: String,
    val title: String,
    val bot_id: String,
    val unread_count: Int,
    val running: Boolean,
    val queued_count: Int,
    val last_sequence: Long,
)

@Serializable
data class GroupChatSummary(val id: String, val title: String, val ownership_bot_id: String, val coordination_max_turns: Int, val coordination_turns_used: Int, val max_parallel_bots: Int, val stop_requested: Boolean)

@Serializable
data class GroupParticipantSummary(val chat_id: String, val bot_id: String, val role: String, val status: String, val active_operation_id: String? = null, val updated_at_ms: Long)

@Serializable
data class OwnershipHandoffSummary(val id: String, val chat_id: String, val from_bot_id: String, val to_bot_id: String, val message_id: String? = null, val reason: String, val created_at_ms: Long)

@Serializable
data class CreateGroupChatRequest(val request_id: String, val idempotency_key: String, val title: String, val bot_ids: List<String>, val ownership_bot_id: String, val coordination_max_turns: Int, val max_parallel_bots: Int)

@Serializable
data class CreateGroupChatResponse(val group: GroupChatSummary, val participants: List<GroupParticipantSummary>)

@Serializable
data class GroupTimelineResponse(val group: GroupChatSummary, val participants: List<GroupParticipantSummary>, val messages: List<MessageSummary>, val handoffs: List<OwnershipHandoffSummary>, val boundary_sequence: Long)

@Serializable
data class SendGroupMessageRequest(val request_id: String, val idempotency_key: String, val content: String, val mentioned_bot_ids: List<String>, val shared_context_message_ids: List<String>)

@Serializable
data class HandoffGroupRequest(val request_id: String, val idempotency_key: String, val from_bot_id: String, val to_bot_id: String, val message_id: String? = null, val reason: String)

@Serializable
data class UpdateGroupParticipantRequest(val request_id: String, val idempotency_key: String, val status: String, val operation_id: String? = null)

@Serializable
data class AddGroupParticipantRequest(val request_id: String, val idempotency_key: String, val bot_id: String)

@Serializable
sealed interface MessagePart {
    @Serializable @SerialName("text")
    data class Text(val id: String, val ordinal: Int, val text: String) : MessagePart
    @Serializable @SerialName("attachment")
    data class AttachmentPart(val id: String, val ordinal: Int, val attachment: Attachment) : MessagePart
    @Serializable @SerialName("notice")
    data class Notice(val id: String, val ordinal: Int, val text: String) : MessagePart
}

@Serializable
data class MessageSummary(
    val id: String,
    val chat_id: String,
    val author: String,
    val author_bot_id: String? = null,
    val status: String,
    val parts: List<MessagePart>,
    val reply_to_message_id: String? = null,
    val mentioned_bot_ids: List<String>,
    val shared_context_message_ids: List<String>,
    val created_at_ms: Long,
    val completed_at_ms: Long? = null,
    val error: ErrorEnvelope? = null,
)

@Serializable
data class ActivityPresentation(val risk: String, val detail: JsonElement, val copy_text: String? = null, val open_artifact_id: String? = null)

@Serializable
data class ActivitySummary(val id: String, val chat_id: String, val message_id: String? = null, val title: String, val detail: String, val kind: String, val presentation: ActivityPresentation, val status: String, val requires_attention: Boolean, val started_at_ms: Long, val finished_at_ms: Long? = null)

@Serializable
data class ArtifactSummary(val id: String, val chat_id: String, val message_id: String? = null, val activity_id: String? = null, val name: String, val kind: String, val media_type: String, val size_bytes: Long, val sha256: String, val created_at_ms: Long)

@Serializable
data class ApprovalSummary(val id: String, val chat_id: String, val message_id: String? = null, val title: String, val detail: String, val status: String, val created_at_ms: Long, val decided_at_ms: Long? = null)

@Serializable
data class ApprovalDecisionRequest(val request_id: String, val idempotency_key: String, val allow: Boolean)

@Serializable
data class QueuedPromptSummary(val id: String, val chat_id: String, val content: String, val attachment_ids: List<String>, val position: Int, val created_at_ms: Long)

@Serializable
data class SecretSummary(val id: String, val label: String, val status: String, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class PluginToolSummary(val name: String, val title: String? = null, val description: String? = null, val input_schema: JsonElement)

@Serializable
data class PluginSummary(val id: String, val name: String, val description: String, val kind: String, val enabled: Boolean, val connection_state: String, val auth_state: String, val error_message: String? = null, val tools: List<PluginToolSummary>, val bot_ids: List<String>, val updated_at_unix_ms: Long)

@Serializable
data class CreateLocalMcpPluginRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val program: String, val arguments: List<String> = emptyList())

@Serializable
data class PluginMutationRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class PluginAssignmentRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val enabled: Boolean)

@Serializable
data class RoutineInput(val key: String, val label: String, val kind: String, val required: Boolean)

@Serializable
data class ExpectedOutput(val key: String, val description: String, val required: Boolean)

@Serializable
data class RoutineDefinition(val inputs: List<RoutineInput>, val steps: List<JsonElement>, val expected_outputs: List<ExpectedOutput>)

@Serializable
data class RecordedAction(val actor: String, val step: JsonElement)

@Serializable
data class RoutineExecutionResult(val step_index: Int, val status: String, val output: JsonElement? = null)

@Serializable
data class RoutineSummary(val id: String, val bot_id: String, val name: String, val description: String, val enabled: Boolean, val draft: Boolean, val active_version_id: String, val version: Int, val definition: RoutineDefinition, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class CreateRoutineRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val name: String, val description: String = "", val definition: RoutineDefinition, val draft: Boolean = true)

@Serializable
data class UpdateRoutineRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val definition: RoutineDefinition, val draft: Boolean)

@Serializable
data class StartRoutineRecordingRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val name: String, val description: String = "")

@Serializable
data class AppendRoutineRecordingRequest(val request_id: String, val idempotency_key: String, val action: RecordedAction)

@Serializable
data class RoutineRecordingSummary(val id: String, val bot_id: String, val name: String, val description: String, val actions: List<RecordedAction>, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class RunRoutineRequest(val request_id: String, val idempotency_key: String, val inputs: JsonElement)

@Serializable
data class RoutineRunSummary(val id: String, val routine_id: String, val routine_version_id: String, val bot_id: String, val status: String, val trigger: JsonElement, val input_metadata: JsonElement, val dry_run: Boolean, val results: List<RoutineExecutionResult>, val error_message: String? = null, val attempt_count: Int, val scheduled_for_unix_ms: Long? = null, val started_at_unix_ms: Long, val finished_at_unix_ms: Long? = null)

@Serializable
data class RoutineTriggerSummary(val id: String, val routine_id: String, val definition: JsonElement, val enabled: Boolean, val last_evaluated_at_unix_ms: Long? = null, val next_fire_at_unix_ms: Long? = null, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class CreateRoutineTriggerRequest(val request_id: String, val idempotency_key: String, val definition: JsonElement, val enabled: Boolean = true)

@Serializable
data class DeliverRoutineTriggerRequest(val request_id: String, val idempotency_key: String, val delivery_key: String, val inputs: JsonElement)

@Serializable
data class RoutineJobSummary(val id: String, val trigger_id: String, val routine_id: String, val routine_version_id: String, val delivery_key: String, val trigger: JsonElement, val input_metadata: JsonElement, val status: String, val attempt_count: Int, val scheduled_for_unix_ms: Long, val next_attempt_at_unix_ms: Long, val cancel_requested: Boolean, val error_message: String? = null, val created_at_unix_ms: Long, val started_at_unix_ms: Long? = null, val finished_at_unix_ms: Long? = null)

@Serializable
class CreateSecretRequest(val request_id: String, val idempotency_key: String, val label: String, val value: String) {
    override fun toString(): String = "CreateSecretRequest(request_id=$request_id, idempotency_key=$idempotency_key, label=$label, value=[REDACTED])"
}

@Serializable
class UpdateSecretRequest(val request_id: String, val label: String? = null, val value: String? = null) {
    override fun toString(): String = "UpdateSecretRequest(request_id=$request_id, label=$label, value=[REDACTED])"
}

@Serializable
data class CreateDirectChatRequest(val request_id: String, val idempotency_key: String, val bot_id: String)

@Serializable
data class CreateDirectChatResponse(val chat: ChatSummary)

@Serializable
data class SendMessageRequest(val request_id: String, val idempotency_key: String, val content: String, val attachment_ids: List<String>, val reply_to_message_id: String? = null, val mentioned_bot_ids: List<String>)

@Serializable
sealed interface SendMessageResponse {
    @Serializable @SerialName("sent")
    data class Sent(val message: MessageSummary) : SendMessageResponse
    @Serializable @SerialName("queued")
    data class Queued(val prompt: QueuedPromptSummary) : SendMessageResponse
}

@Serializable
data class ChatTimelineResponse(val chat: ChatSummary, val messages: List<MessageSummary>, val activities: List<ActivitySummary>, val approvals: List<ApprovalSummary>, val queued_prompts: List<QueuedPromptSummary>, val boundary_sequence: Long)

@Serializable
data class CreateAttachmentRequest(val request_id: String, val idempotency_key: String, val filename: String, val media_type: String, val size_bytes: Long, val sha256: String)

@Serializable
data class FinalizeAttachmentRequest(val request_id: String, val idempotency_key: String, val sha256: String)
"#;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let destination = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../android/protocol/src/main/kotlin/dev/homebot/protocol/ProtocolV1.kt");
    if env::args().any(|argument| argument == "--check") {
        if fs::read_to_string(&destination)? != GENERATED {
            return Err("Android protocol binding is stale; regenerate it".into());
        }
    } else {
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(destination, GENERATED)?;
    }
    Ok(())
}
