use std::{env, fs, path::PathBuf};

const GENERATED: &str = r#"// Generated by homebot-protocol/examples/export_android.rs. Do not edit.
package dev.homebot.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

const val PROTOCOL_VERSION: Int = 1

@Serializable
data class ProtocolRange(val minimum: Int, val maximum: Int)

@Serializable
enum class ResumeDisposition { @SerialName("replayed") REPLAYED, @SerialName("snapshot_required") SNAPSHOT_REQUIRED }

@Serializable
sealed interface ClientMessage {
    @Serializable @SerialName("hello")
    data class Hello(val protocol_version: Int, val client_version: String, val device_session: String, val resume_after: Long? = null) : ClientMessage
    @Serializable @SerialName("command")
    data class Command(val request_id: String, val idempotency_key: String, val command: CommandBody) : ClientMessage
    @Serializable @SerialName("cancel")
    data class Cancel(val request_id: String, val operation_id: String) : ClientMessage
    @Serializable @SerialName("pong")
    data class Pong(val nonce: String) : ClientMessage
}

@Serializable
sealed interface CommandBody {
    @Serializable @SerialName("create_bot")
    data class CreateBot(val name: String, val title: String) : CommandBody
    @Serializable @SerialName("send_message")
    data class SendMessage(val chat_id: String, val content: String) : CommandBody
}

@Serializable
data class ServerEvent(
    val protocol_version: Int,
    val sequence: Long,
    val event_id: String,
    val kind: String,
    val request_id: String? = null,
    val operation_id: String? = null,
    val payload: JsonElement? = null,
)

@Serializable
data class ErrorEnvelope(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val request_id: String? = null,
    val retry_after_ms: Long? = null,
    val details: JsonElement? = null,
)

@Serializable
data class Snapshot(
    val bots: List<BotSummary> = emptyList(),
    val chats: List<ChatSummary> = emptyList(),
    val group_chats: List<GroupChatSummary> = emptyList(),
    val skills: List<SkillSummary> = emptyList(),
    val repository_workspaces: List<RepositoryWorkspaceSummary> = emptyList(),
    val chat_workspaces: List<ChatWorkspaceSummary> = emptyList(),
    val capability_rules: List<CapabilityRuleSummary> = emptyList(),
    val browser_sessions: List<BrowserSessionSummary> = emptyList(),
    val provider_profiles: List<ProviderProfileSummary> = emptyList(),
)

@Serializable
data class ProviderProfileSummary(
    val id: String,
    val adapter_id: String,
    val kind: String,
    val display_name: String,
    val availability: String,
    val status_message: String,
    val capabilities: List<String> = emptyList(),
)

@Serializable
data class BotAdvancedSettings(
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class BotSummary(
    val id: String,
    val name: String,
    val title: String,
    val description: String,
    val shape: String,
    val color: String,
    val archived: Boolean,
    val pinned: Boolean = false,
    val hidden: Boolean = false,
    val unread_count: Int,
    val attention: String,
    val provider: String,
    val advanced: BotAdvancedSettings,
)

@Serializable
data class CreateBotRequest(
    val request_id: String,
    val idempotency_key: String,
    val name: String,
    val title: String,
    val description: String = "",
    val shape: String,
    val color: String,
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class UpdateBotRequest(
    val request_id: String,
    val idempotency_key: String,
    val name: String,
    val title: String,
    val description: String = "",
    val shape: String,
    val color: String,
    val provider_profile_id: String? = null,
    val permission_profile: String,
)

@Serializable
data class BotMutationRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class DeleteBotRequest(val request_id: String, val idempotency_key: String, val confirm_name: String)

@Serializable
enum class PairingEndpointKind { @SerialName("loopback") LOOPBACK, @SerialName("lan") LAN, @SerialName("tailscale") TAILSCALE, @SerialName("custom_https") CUSTOM_HTTPS }

@Serializable
data class CreatePairingRequest(val request_id: String, val endpoint: String, val allow_insecure_private_network: Boolean = false)

@Serializable
data class PairingOffer(val id: String, val endpoint: String, val endpoint_kind: PairingEndpointKind, val pairing_token: String, val deep_link: String, val expires_at_unix_ms: Long, val warning: String? = null)

@Serializable
data class ExchangePairingRequest(val request_id: String, val pairing_token: String, val native_proof: String? = null, val device_name: String)

@Serializable
data class DeviceSessionSummary(val id: String, val name: String, val endpoint_kind: PairingEndpointKind, val created_at_unix_ms: Long, val last_seen_at_unix_ms: Long? = null, val revoked_at_unix_ms: Long? = null)

@Serializable
data class PairingExchangeResponse(val device: DeviceSessionSummary, val device_session: String)

@Serializable
data class RevokeDeviceSessionRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class BotResponse(val bot: BotSummary)

@Serializable
data class ChatSummary(
    val id: String,
    val title: String,
    val bot_id: String,
    val unread_count: Int,
    val running: Boolean,
    val queued_count: Int,
    val last_sequence: Long,
)

@Serializable
data class GroupChatSummary(val id: String, val title: String, val ownership_bot_id: String, val coordination_max_turns: Int, val coordination_turns_used: Int, val max_parallel_bots: Int, val stop_requested: Boolean)

@Serializable
data class GroupParticipantSummary(val chat_id: String, val bot_id: String, val role: String, val status: String, val active_operation_id: String? = null, val updated_at_ms: Long)

@Serializable
data class OwnershipHandoffSummary(val id: String, val chat_id: String, val from_bot_id: String, val to_bot_id: String, val message_id: String? = null, val reason: String, val created_at_ms: Long)

@Serializable
data class CreateGroupChatRequest(val request_id: String, val idempotency_key: String, val title: String, val bot_ids: List<String>, val ownership_bot_id: String, val coordination_max_turns: Int, val max_parallel_bots: Int)

@Serializable
data class RenameGroupChatRequest(val request_id: String, val idempotency_key: String, val title: String)

@Serializable
data class CreateGroupChatResponse(val group: GroupChatSummary, val participants: List<GroupParticipantSummary>)

@Serializable
data class GroupTimelineResponse(val group: GroupChatSummary, val participants: List<GroupParticipantSummary>, val messages: List<MessageSummary>, val handoffs: List<OwnershipHandoffSummary>, val boundary_sequence: Long)

@Serializable
data class SendGroupMessageRequest(val request_id: String, val idempotency_key: String, val content: String, val mentioned_bot_ids: List<String>, val shared_context_message_ids: List<String>, val reply_to_message_id: String? = null, val references: List<MessageReferenceInput> = emptyList())

@Serializable
data class HandoffGroupRequest(val request_id: String, val idempotency_key: String, val from_bot_id: String, val to_bot_id: String, val message_id: String? = null, val reason: String)

@Serializable
data class UpdateGroupParticipantRequest(val request_id: String, val idempotency_key: String, val status: String, val operation_id: String? = null)

@Serializable
data class AddGroupParticipantRequest(val request_id: String, val idempotency_key: String, val bot_id: String)

@Serializable
data class Attachment(val id: String, val filename: String, val media_type: String, val size_bytes: Long, val sha256: String)

@Serializable
sealed interface MessagePart {
    @Serializable @SerialName("text")
    data class Text(val id: String, val ordinal: Int, val text: String) : MessagePart
    @Serializable @SerialName("attachment")
    data class AttachmentPart(val id: String, val ordinal: Int, val attachment: Attachment) : MessagePart
    @Serializable @SerialName("notice")
    data class Notice(val id: String, val ordinal: Int, val text: String) : MessagePart
}

@Serializable
data class MessageSummary(
    val id: String,
    val chat_id: String,
    val author: String,
    val author_bot_id: String? = null,
    val status: String,
    val parts: List<MessagePart>,
    val reply_to_message_id: String? = null,
    val mentioned_bot_ids: List<String>,
    val shared_context_message_ids: List<String>,
    val applied_skills: List<AppliedSkillSummary> = emptyList(),
    val reactions: List<ReactionSummary> = emptyList(),
    val references: List<MessageReferenceSummary> = emptyList(),
    val created_at_ms: Long,
    val completed_at_ms: Long? = null,
    val error: ErrorEnvelope? = null,
)

@Serializable
data class ReactionSummary(val emoji: String, val count: Int, val reacted_by_user: Boolean)

@Serializable
enum class MessageReferenceKind { @SerialName("bot") BOT, @SerialName("group") GROUP, @SerialName("routine") ROUTINE, @SerialName("plugin") PLUGIN }

@Serializable
data class MessageReferenceInput(val kind: MessageReferenceKind, val target_id: String)

@Serializable
data class MessageReferenceSummary(val kind: MessageReferenceKind, val target_id: String, val target_version_id: String? = null, val label: String)

@Serializable
enum class SearchResultKind { @SerialName("message") MESSAGE, @SerialName("file") FILE, @SerialName("link") LINK, @SerialName("routine") ROUTINE }

@Serializable
data class SearchResultSummary(val kind: SearchResultKind, val title: String, val snippet: String, val deep_link: String, val chat_id: String? = null, val message_id: String? = null, val artifact_id: String? = null, val routine_id: String? = null, val created_at_ms: Long)

@Serializable
data class GlobalSearchResponse(val query: String, val results: List<SearchResultSummary>)

@Serializable
data class ReactionMutationRequest(val request_id: String, val idempotency_key: String, val emoji: String)

@Serializable
data class ActivityPresentation(val risk: String, val detail: JsonElement, val copy_text: String? = null, val open_artifact_id: String? = null)

@Serializable
data class ActivitySummary(val id: String, val chat_id: String, val message_id: String? = null, val title: String, val detail: String, val kind: String, val presentation: ActivityPresentation, val status: String, val requires_attention: Boolean, val started_at_ms: Long, val finished_at_ms: Long? = null)

@Serializable
data class ArtifactSummary(val id: String, val chat_id: String, val message_id: String? = null, val activity_id: String? = null, val name: String, val kind: String, val media_type: String, val size_bytes: Long, val sha256: String, val created_at_ms: Long)

@Serializable
data class ApprovalSummary(val id: String, val chat_id: String, val message_id: String? = null, val title: String, val detail: String, val status: String, val created_at_ms: Long, val decided_at_ms: Long? = null)

@Serializable
data class ApprovalDecisionRequest(val request_id: String, val idempotency_key: String, val allow: Boolean)

@Serializable
enum class CapabilityClass { @SerialName("filesystem_read") FILESYSTEM_READ, @SerialName("filesystem_write") FILESYSTEM_WRITE, @SerialName("process_execute") PROCESS_EXECUTE, @SerialName("browser_observe") BROWSER_OBSERVE, @SerialName("browser_act") BROWSER_ACT, @SerialName("git_read") GIT_READ, @SerialName("git_write") GIT_WRITE, @SerialName("git_remote") GIT_REMOTE, @SerialName("plugin_read") PLUGIN_READ, @SerialName("plugin_write") PLUGIN_WRITE, @SerialName("external_communication") EXTERNAL_COMMUNICATION, @SerialName("external_mutation") EXTERNAL_MUTATION, @SerialName("secret_use") SECRET_USE, @SerialName("device_administration") DEVICE_ADMINISTRATION }

@Serializable
enum class CapabilityRuleEffect { @SerialName("allow") ALLOW, @SerialName("require_approval") REQUIRE_APPROVAL, @SerialName("deny") DENY }

@Serializable
data class CapabilityRuleSummary(val id: String, val capability: CapabilityClass, val effect: CapabilityRuleEffect, val device_id: String? = null, val bot_id: String? = null, val chat_id: String? = null, val workspace_id: String? = null, val action_prefix: String? = null, val created_at_ms: Long, val updated_at_ms: Long)

@Serializable
data class UpsertCapabilityRuleRequest(val request_id: String, val idempotency_key: String, val capability: CapabilityClass, val effect: CapabilityRuleEffect, val device_id: String? = null, val bot_id: String? = null, val chat_id: String? = null, val workspace_id: String? = null, val action_prefix: String? = null)

@Serializable
data class CapabilityRuleAuditSummary(val id: String, val rule_id: String, val action: String, val snapshot: JsonElement, val created_at_ms: Long)

@Serializable
enum class BrowserController { @SerialName("bot") BOT, @SerialName("user") USER }

@Serializable
enum class BrowserSessionStatus { @SerialName("active") ACTIVE, @SerialName("awaiting_approval") AWAITING_APPROVAL, @SerialName("closed") CLOSED, @SerialName("failed") FAILED }

@Serializable
data class BrowserSessionSummary(val id: String, val chat_id: String, val bot_id: String, val profile_id: String, val profile_name: String, val current_url: String? = null, val controller: BrowserController, val status: BrowserSessionStatus, val pending_approval_id: String? = null, val created_at_ms: Long, val updated_at_ms: Long)

@Serializable
data class CreateBrowserSessionRequest(val request_id: String, val idempotency_key: String, val chat_id: String, val bot_id: String, val profile_id: String, val profile_name: String, val approval_id: String? = null)

@Serializable
data class BrowserMutationRequest(val request_id: String, val idempotency_key: String, val approval_id: String? = null)

@Serializable
sealed interface BrowserCommand {
    @Serializable @SerialName("navigate") data class Navigate(val url: String) : BrowserCommand
    @Serializable @SerialName("current_url") data object CurrentUrl : BrowserCommand
    @Serializable @SerialName("capture_screenshot") data object CaptureScreenshot : BrowserCommand
}

@Serializable
data class BrowserActionRequest(val request_id: String, val idempotency_key: String, val command: BrowserCommand, val approval_id: String? = null)

@Serializable
data class BrowserActionResponse(val session: BrowserSessionSummary, val approval: ApprovalSummary? = null, val artifact: ArtifactSummary? = null)

@Serializable
enum class QueuedPromptKind { @SerialName("follow_up") FOLLOW_UP, @SerialName("steering") STEERING }

@Serializable
data class QueuedPromptSummary(val id: String, val chat_id: String, val content: String, val attachment_ids: List<String>, val skill_ids: List<String> = emptyList(), val kind: QueuedPromptKind = QueuedPromptKind.FOLLOW_UP, val position: Int, val created_at_ms: Long)

@Serializable
enum class InteractionMode { @SerialName("default") DEFAULT, @SerialName("plan") PLAN }

@Serializable
enum class ContextCompactionStatus { @SerialName("idle") IDLE, @SerialName("running") RUNNING, @SerialName("completed") COMPLETED, @SerialName("failed") FAILED }

@Serializable
enum class ContextCompactionStrategy { @SerialName("compact") COMPACT, @SerialName("reset") RESET }

@Serializable
data class WorkingContextSummary(val chat_id: String, val provider_profile_id: String, val interaction_mode: InteractionMode, val plan_mode_available: Boolean, val compaction_available: Boolean, val reset_available: Boolean, val used_tokens: Long? = null, val context_window_tokens: Long? = null, val compaction_status: ContextCompactionStatus, val generation: Int, val compacted_at_ms: Long? = null, val error_message: String? = null, val updated_at_ms: Long)

@Serializable
data class SetInteractionModeRequest(val request_id: String, val idempotency_key: String, val mode: InteractionMode)

@Serializable
data class CompactWorkingContextRequest(val request_id: String, val idempotency_key: String, val strategy: ContextCompactionStrategy, val target_tokens: Long? = null)

@Serializable
data class SecretSummary(val id: String, val label: String, val status: String, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class PluginToolSummary(val name: String, val title: String? = null, val description: String? = null, val input_schema: JsonElement)

@Serializable
data class PluginSummary(val id: String, val name: String, val description: String, val kind: String, val enabled: Boolean, val connection_state: String, val auth_state: String, val error_message: String? = null, val tools: List<PluginToolSummary>, val bot_ids: List<String>, val updated_at_unix_ms: Long)

@Serializable
data class CreateLocalMcpPluginRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val program: String, val arguments: List<String> = emptyList())

@Serializable
data class PluginMutationRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class PluginAssignmentRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val enabled: Boolean)

@Serializable
data class SkillContext(val label: String, val content: String)

@Serializable
data class SkillToolReference(val plugin_name: String, val tool_name: String)

@Serializable
data class SkillDefinition(val instructions: String, val context: List<SkillContext> = emptyList(), val tools: List<SkillToolReference> = emptyList())

@Serializable
data class AppliedSkillSummary(val skill_id: String, val skill_version_id: String, val name: String, val version: Int)

@Serializable
data class SkillSummary(val id: String, val name: String, val description: String, val active_version_id: String, val version: Int, val definition: SkillDefinition, val bot_ids: List<String>, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class CreateSkillRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val definition: SkillDefinition)

@Serializable
data class UpdateSkillRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val definition: SkillDefinition)

@Serializable
data class DuplicateSkillRequest(val request_id: String, val idempotency_key: String, val name: String)

@Serializable
data class SkillAssignmentRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val enabled: Boolean)

@Serializable
data class SkillTestSummary(val skill_id: String, val skill_version_id: String, val version: Int, val prompt_preview: String, val capability_policy_enforced: Boolean)

@Serializable
data class SkillBundle(val format_version: Int, val name: String, val description: String, val definition: SkillDefinition)

@Serializable
data class ImportSkillRequest(val request_id: String, val idempotency_key: String, val bundle: SkillBundle, val conflict_policy: String)

@Serializable
data class RepositoryWorkspaceSummary(val id: String, val name: String, val root_path: String, val current_branch: String? = null, val condition: String, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class ChatWorkspaceSummary(val chat_id: String, val workspace_id: String, val mode: String, val effective_path: String, val branch_name: String? = null, val base_ref: String? = null, val condition: String, val updated_at_unix_ms: Long)

@Serializable
data class CreateRepositoryWorkspaceRequest(val request_id: String, val idempotency_key: String, val root_path: String, val name: String? = null)

@Serializable
data class AttachChatWorkspaceRequest(val request_id: String, val idempotency_key: String, val workspace_id: String, val mode: String, val base_ref: String? = null, val branch_name: String? = null)

@Serializable
data class DetachChatWorkspaceRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class WorkspaceBranchesResponse(val branches: List<String>)

@Serializable
data class VcsStatusEntry(val path: String, val previous_path: String? = null, val staged: String? = null, val unstaged: String? = null, val conflicted: Boolean)

@Serializable
data class VcsRemoteSummary(val name: String, val fetch_configured: Boolean, val push_configured: Boolean)

@Serializable
data class VcsStatus(val head_oid: String? = null, val branch: String? = null, val detached: Boolean, val upstream: String? = null, val ahead: Int, val behind: Int, val conflicted: Boolean, val entries: List<VcsStatusEntry>, val remotes: List<VcsRemoteSummary>)

@Serializable
data class WorkingTreeDiffResponse(val staged: Boolean, val patch: String, val files: List<FileChange>)

@Serializable
data class VcsCommitRequest(val request_id: String, val idempotency_key: String, val message: String, val stage_all: Boolean)

@Serializable
data class VcsCommitResult(val commit_oid: String, val branch: String? = null)

@Serializable
data class VcsCreateBranchRequest(val request_id: String, val idempotency_key: String, val branch: String, val start_point: String? = null)

@Serializable
data class VcsPushRequest(val request_id: String, val idempotency_key: String, val remote: String, val branch: String, val set_upstream: Boolean, val approval_id: String? = null)

@Serializable
data class VcsPushResult(val remote: String, val branch: String, val updated: Boolean)

@Serializable
data class VcsRemoteMutationResponse(val status: String, val approval: ApprovalSummary? = null, val result: VcsPushResult? = null)

@Serializable
data class PullRequestSummary(val number: Long, val url: String, val title: String, val state: String, val head_branch: String, val base_branch: String)

@Serializable
data class PullRequestMetadata(val remote: String, val provider: String, val repository: String? = null, val head_branch: String, val base_branch: String, val compare_url: String? = null, val create_available: Boolean, val current: PullRequestSummary? = null)

@Serializable
data class CreatePullRequestRequest(val request_id: String, val idempotency_key: String, val remote: String, val head_branch: String, val base_branch: String, val title: String, val body: String, val draft: Boolean, val approval_id: String? = null)

@Serializable
data class PullRequestMutationResponse(val status: String, val approval: ApprovalSummary? = null, val result: PullRequestSummary? = null)

@Serializable
data class TurnCheckpointSummary(val id: String, val chat_id: String, val workspace_id: String, val message_id: String? = null, val phase: String, val created_at_unix_ms: Long)

@Serializable
data class FileChange(val status: String, val path: String, val previous_path: String? = null, val binary: Boolean)

@Serializable
data class CheckpointDiffResponse(val from_checkpoint_id: String, val to_checkpoint_id: String, val patch: String, val files: List<FileChange>)

@Serializable
data class RestoreCheckpointRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class CheckpointRestoreSummary(val id: String, val chat_id: String, val checkpoint_id: String, val safety_checkpoint_id: String, val reconciliation: String, val created_at_unix_ms: Long)

@Serializable
data class RoutineInput(val key: String, val label: String, val kind: String, val required: Boolean)

@Serializable
data class ExpectedOutput(val key: String, val description: String, val required: Boolean)

@Serializable
data class RoutineDefinition(val inputs: List<RoutineInput>, val steps: List<JsonElement>, val expected_outputs: List<ExpectedOutput>)

@Serializable
data class RecordedAction(val actor: String, val step: JsonElement)

@Serializable
data class RoutineExecutionResult(val step_index: Int, val status: String, val output: JsonElement? = null)

@Serializable
data class RoutineSummary(val id: String, val bot_id: String, val name: String, val description: String, val enabled: Boolean, val draft: Boolean, val active_version_id: String, val version: Int, val definition: RoutineDefinition, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class CreateRoutineRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val name: String, val description: String = "", val definition: RoutineDefinition, val draft: Boolean = true)

@Serializable
data class UpdateRoutineRequest(val request_id: String, val idempotency_key: String, val name: String, val description: String = "", val definition: RoutineDefinition, val draft: Boolean)

@Serializable
data class DuplicateRoutineRequest(val request_id: String, val idempotency_key: String, val name: String)

@Serializable
data class StartRoutineRecordingRequest(val request_id: String, val idempotency_key: String, val bot_id: String, val name: String, val description: String = "")

@Serializable
data class AppendRoutineRecordingRequest(val request_id: String, val idempotency_key: String, val action: RecordedAction)

@Serializable
data class RoutineRecordingSummary(val id: String, val bot_id: String, val name: String, val description: String, val actions: List<RecordedAction>, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class RunRoutineRequest(val request_id: String, val idempotency_key: String, val inputs: JsonElement)

@Serializable
data class RoutineRunSummary(val id: String, val routine_id: String, val routine_version_id: String, val bot_id: String, val status: String, val trigger: JsonElement, val input_metadata: JsonElement, val dry_run: Boolean, val results: List<RoutineExecutionResult>, val error_message: String? = null, val attempt_count: Int, val scheduled_for_unix_ms: Long? = null, val started_at_unix_ms: Long, val finished_at_unix_ms: Long? = null)

@Serializable
data class RoutineTriggerSummary(val id: String, val routine_id: String, val definition: JsonElement, val enabled: Boolean, val last_evaluated_at_unix_ms: Long? = null, val next_fire_at_unix_ms: Long? = null, val created_at_unix_ms: Long, val updated_at_unix_ms: Long)

@Serializable
data class CreateRoutineTriggerRequest(val request_id: String, val idempotency_key: String, val definition: JsonElement, val enabled: Boolean = true)

@Serializable
data class DeliverRoutineTriggerRequest(val request_id: String, val idempotency_key: String, val delivery_key: String, val inputs: JsonElement)

@Serializable
data class RoutineJobSummary(val id: String, val trigger_id: String, val routine_id: String, val routine_version_id: String, val delivery_key: String, val trigger: JsonElement, val input_metadata: JsonElement, val status: String, val attempt_count: Int, val scheduled_for_unix_ms: Long, val next_attempt_at_unix_ms: Long, val cancel_requested: Boolean, val error_message: String? = null, val created_at_unix_ms: Long, val started_at_unix_ms: Long? = null, val finished_at_unix_ms: Long? = null)

@Serializable
class CreateSecretRequest(val request_id: String, val idempotency_key: String, val label: String, val value: String) {
    override fun toString(): String = "CreateSecretRequest(request_id=$request_id, idempotency_key=$idempotency_key, label=$label, value=[REDACTED])"
}

@Serializable
class UpdateSecretRequest(val request_id: String, val label: String? = null, val value: String? = null) {
    override fun toString(): String = "UpdateSecretRequest(request_id=$request_id, label=$label, value=[REDACTED])"
}

@Serializable
data class CreateDirectChatRequest(val request_id: String, val idempotency_key: String, val bot_id: String)

@Serializable
data class CreateDirectChatResponse(val chat: ChatSummary)

@Serializable
data class SendMessageRequest(val request_id: String, val idempotency_key: String, val content: String, val attachment_ids: List<String>, val reply_to_message_id: String? = null, val mentioned_bot_ids: List<String>, val skill_ids: List<String> = emptyList(), val references: List<MessageReferenceInput> = emptyList())

@Serializable
sealed interface SendMessageResponse {
    @Serializable @SerialName("sent")
    data class Sent(val message: MessageSummary) : SendMessageResponse
    @Serializable @SerialName("queued")
    data class Queued(val prompt: QueuedPromptSummary) : SendMessageResponse
}

@Serializable
data class MessageMutationRequest(val request_id: String, val idempotency_key: String)

@Serializable
data class ChatTimelineResponse(val chat: ChatSummary, val messages: List<MessageSummary>, val activities: List<ActivitySummary>, val approvals: List<ApprovalSummary>, val queued_prompts: List<QueuedPromptSummary>, val working_context: WorkingContextSummary? = null, val checkpoints: List<TurnCheckpointSummary> = emptyList(), val boundary_sequence: Long)

@Serializable
data class CreateAttachmentRequest(val request_id: String, val idempotency_key: String, val filename: String, val media_type: String, val size_bytes: Long, val sha256: String)

@Serializable
data class CreateAttachmentResponse(val attachment_id: String, val upload_url: String, val expires_at_unix_ms: Long)

@Serializable
data class FinalizeAttachmentRequest(val request_id: String, val idempotency_key: String, val sha256: String)
"#;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let destination = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../android/protocol/src/main/kotlin/dev/homebot/protocol/ProtocolV1.kt");
    if env::args().any(|argument| argument == "--check") {
        if fs::read_to_string(&destination)? != GENERATED {
            return Err("Android protocol binding is stale; regenerate it".into());
        }
    } else {
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(destination, GENERATED)?;
    }
    Ok(())
}
