//! Server-authoritative generated artifact storage and retrieval.

use super::{AppState, unix_time_ms};
use axum::{
    Json,
    body::Body,
    extract::{Path as AxumPath, State},
    http::{StatusCode, header},
    response::{IntoResponse, Response},
};
use homebot_protocol::{ArtifactSummary, ErrorCode, ErrorEnvelope};
use homebot_storage::ArtifactRecord;
use sha2::{Digest, Sha256};
use std::path::{Component, Path, PathBuf};
use tokio::io::AsyncWriteExt;
use uuid::Uuid;

const MAX_ARTIFACT_BYTES: usize = 25 * 1024 * 1024;

#[derive(Debug, thiserror::Error)]
pub enum ArtifactStoreError {
    #[error("artifact metadata is invalid")]
    InvalidMetadata,
    #[error("artifact exceeds the bounded storage limit")]
    TooLarge,
    #[error("artifact storage failed: {0}")]
    Io(#[from] std::io::Error),
    #[error("artifact metadata persistence failed")]
    Storage,
}

#[derive(Clone, Copy, Debug)]
pub struct GeneratedArtifact<'a> {
    pub chat_id: Uuid,
    pub message_id: Option<Uuid>,
    pub activity_id: Option<Uuid>,
    pub name: &'a str,
    pub kind: &'a str,
    pub media_type: &'a str,
    pub bytes: &'a [u8],
}

/// Persists bytes generated by a provider or approved tool under a server-owned path.
///
/// Client-provided filesystem paths are never accepted or returned.
///
/// # Errors
///
/// Returns an error when metadata is unsafe, content is too large, the content-addressed write
/// fails, or the owner-scoped metadata cannot be persisted.
pub async fn persist_generated_artifact(
    state: &AppState,
    artifact: GeneratedArtifact<'_>,
) -> Result<ArtifactSummary, ArtifactStoreError> {
    let name = artifact.name.trim();
    let kind = artifact.kind.trim();
    let media_type = artifact.media_type.trim().to_ascii_lowercase();
    if !valid_basename(name)
        || kind.is_empty()
        || kind.len() > 64
        || !kind.is_ascii()
        || media_type.len() > 127
        || !media_type.is_ascii()
        || !media_type.contains('/')
    {
        return Err(ArtifactStoreError::InvalidMetadata);
    }
    if artifact.bytes.len() > MAX_ARTIFACT_BYTES {
        return Err(ArtifactStoreError::TooLarge);
    }

    let id = Uuid::now_v7();
    let sha256 = format!("{:x}", Sha256::digest(artifact.bytes));
    let relative = PathBuf::from("generated").join(&sha256[..2]).join(&sha256);
    let target = state.artifact_root.join(&relative);
    if let Some(parent) = target.parent() {
        tokio::fs::create_dir_all(parent).await?;
    }
    if !tokio::fs::try_exists(&target).await? {
        let temporary = state
            .artifact_root
            .join("generated")
            .join(format!(".{id}.partial"));
        let mut file = tokio::fs::File::create(&temporary).await?;
        file.write_all(artifact.bytes).await?;
        file.flush().await?;
        file.sync_all().await?;
        drop(file);
        if let Err(error) = tokio::fs::rename(&temporary, &target).await {
            let _ = tokio::fs::remove_file(&temporary).await;
            return Err(error.into());
        }
    }
    let record = ArtifactRecord {
        id,
        owner_id: state.owner_id,
        chat_id: artifact.chat_id,
        message_id: artifact.message_id,
        activity_id: artifact.activity_id,
        name: name.to_owned(),
        kind: kind.to_owned(),
        media_type,
        size_bytes: u64::try_from(artifact.bytes.len()).unwrap_or(u64::MAX),
        sha256,
        storage_path: relative.to_string_lossy().into_owned(),
        created_at_ms: unix_time_ms(),
    };
    state
        .storage
        .insert_artifact(&record)
        .await
        .map_err(|_| ArtifactStoreError::Storage)?;
    Ok(protocol_artifact(&record))
}

pub(super) async fn metadata(
    State(state): State<AppState>,
    AxumPath(artifact_id): AxumPath<Uuid>,
) -> Response {
    match state.storage.artifact(state.owner_id, artifact_id).await {
        Ok(Some(record)) => Json(protocol_artifact(&record)).into_response(),
        Ok(None) => not_found(),
        Err(_) => internal_error(),
    }
}

pub(super) async fn content(
    State(state): State<AppState>,
    AxumPath(artifact_id): AxumPath<Uuid>,
) -> Response {
    let record = match state.storage.artifact(state.owner_id, artifact_id).await {
        Ok(Some(record)) => record,
        Ok(None) => return not_found(),
        Err(_) => return internal_error(),
    };
    let relative = Path::new(&record.storage_path);
    if relative.is_absolute()
        || relative.components().any(|component| {
            matches!(
                component,
                Component::ParentDir | Component::RootDir | Component::Prefix(_)
            )
        })
    {
        return internal_error();
    }
    let Ok(bytes) = tokio::fs::read(state.artifact_root.join(relative)).await else {
        return internal_error();
    };
    let mut response = Response::new(Body::from(bytes));
    *response.status_mut() = StatusCode::OK;
    if let Ok(value) = record.media_type.parse() {
        response.headers_mut().insert(header::CONTENT_TYPE, value);
    }
    response
}

fn protocol_artifact(record: &ArtifactRecord) -> ArtifactSummary {
    ArtifactSummary {
        id: record.id,
        chat_id: record.chat_id,
        message_id: record.message_id,
        activity_id: record.activity_id,
        name: record.name.clone(),
        kind: record.kind.clone(),
        media_type: record.media_type.clone(),
        size_bytes: record.size_bytes,
        sha256: record.sha256.clone(),
        created_at_ms: record.created_at_ms,
    }
}

fn valid_basename(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 255
        && !value.contains(['/', '\\', '\0'])
        && value != "."
        && value != ".."
}

fn not_found() -> Response {
    (
        StatusCode::NOT_FOUND,
        Json(ErrorEnvelope {
            code: ErrorCode::NotFound,
            message: "Artifact was not found".to_owned(),
            retryable: false,
            request_id: None,
            retry_after_ms: None,
            details: None,
        }),
    )
        .into_response()
}

fn internal_error() -> Response {
    (
        StatusCode::INTERNAL_SERVER_ERROR,
        Json(ErrorEnvelope {
            code: ErrorCode::Internal,
            message: "HomeBot could not read the artifact".to_owned(),
            retryable: false,
            request_id: None,
            retry_after_ms: None,
            details: None,
        }),
    )
        .into_response()
}
