// Generated by homebot-protocol/examples/export_android.rs. Do not edit.
package dev.homebot.protocol

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

const val PROTOCOL_VERSION: Int = 1

@Serializable
sealed interface ClientMessage {
    @Serializable @SerialName("hello")
    data class Hello(val protocol_version: Int, val client_version: String, val device_session: String, val resume_after: Long? = null) : ClientMessage
    @Serializable @SerialName("command")
    data class Command(val request_id: String, val idempotency_key: String, val command: CommandBody) : ClientMessage
    @Serializable @SerialName("cancel")
    data class Cancel(val request_id: String, val operation_id: String) : ClientMessage
    @Serializable @SerialName("pong")
    data class Pong(val nonce: String) : ClientMessage
}

@Serializable
sealed interface CommandBody {
    @Serializable @SerialName("create_bot")
    data class CreateBot(val name: String, val title: String) : CommandBody
    @Serializable @SerialName("send_message")
    data class SendMessage(val chat_id: String, val content: String) : CommandBody
}

@Serializable
data class ServerEvent(
    val protocol_version: Int,
    val sequence: Long,
    val event_id: String,
    val kind: String,
    val request_id: String? = null,
    val operation_id: String? = null,
    val payload: JsonElement? = null,
)

@Serializable
data class ErrorEnvelope(
    val code: String,
    val message: String,
    val retryable: Boolean,
    val request_id: String? = null,
    val retry_after_ms: Long? = null,
    val details: JsonElement? = null,
)

@Serializable
data class CreateAttachmentRequest(val request_id: String, val idempotency_key: String, val filename: String, val media_type: String, val size_bytes: Long, val sha256: String)

@Serializable
data class FinalizeAttachmentRequest(val request_id: String, val idempotency_key: String, val sha256: String)
